import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Gaya CSS untuk PDF
const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 12, fontFamily: 'Helvetica' },
  header: { fontSize: 18, marginBottom: 20, textAlign: 'center', fontWeight: 'bold', color: '#1a365d' },
  section: { marginBottom: 10 },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 5 },
  label: { width: '30%', fontWeight: 'bold', color: '#4a5568' },
  value: { width: '70%' },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 10, color: 'grey' }
});

export const BiodataPDF = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* JUDUL */}
      <Text style={styles.header}>BIODATA KANDIDAT TAIWAN</Text>
      
      {/* INFORMASI UTAMA */}
      <View style={{borderTopWidth: 2, borderTopColor: '#1a365d', marginBottom: 20}}>
        
        <View style={styles.row}>
          <Text style={styles.label}>Nama Lengkap</Text>
          <Text style={styles.value}>{data.fullName}</Text>
        </View>
        
        <View style={styles.row}>
          <Text style={styles.label}>Jenis Kelamin</Text>
          <Text style={styles.value}>{data.gender}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Tanggal Lahir</Text>
          <Text style={styles.value}>{data.birthDate}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Tinggi / Berat</Text>
          <Text style={styles.value}>{data.height} cm / {data.weight} kg</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Agama</Text>
          <Text style={styles.value}>{data.religion}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Status Pernikahan</Text>
          <Text style={styles.value}>{data.status}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Pendidikan Terakhir</Text>
          <Text style={styles.value}>{data.education}</Text>
        </View>
        
        <View style={styles.row}>
          <Text style={styles.label}>Nomor HP / WA</Text>
          <Text style={styles.value}>{data.phone}</Text>
        </View>

      </View>

      {/* SKILL & BAHASA */}
      <Text style={{fontSize: 14, fontWeight: 'bold', marginBottom: 10, marginTop: 10, color: '#1a365d'}}>KEMAMPUAN</Text>
      
      <View style={{borderTopWidth: 1, borderTopColor: '#ccc'}}>
        <View style={styles.row}>
          <Text style={styles.label}>Bahasa Mandarin</Text>
          <Text style={styles.value}>{data.mandarin}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Keahlian Khusus</Text>
          <Text style={styles.value}>{data.skill}</Text>
        </View>
      </View>

      <Text style={styles.footer}>
        Generated by TaiwanInsider.com - {new Date().toLocaleDateString()}
      </Text>

    </Page>
  </Document>
);